name: Youtube To Anchor Bot
on:
  push:
    paths:
      - 'episode.json'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install Dependencies
        run: |
          npm install
          sudo apt-get update
          sudo apt-get -y install ffmpeg
      - name: Get last video ID
        run: |
          echo "LAST_VIDEO_ID=$(node -p "require('./src/youtube-new-video/index.js').lastVideoData.videoId")" >> $GITHUB_ENV
      - name: Run Script
        run: |
          npm run start
        env:
          ANCHOR_EMAIL: ${{ secrets.ANCHOR_EMAIL }}
          ANCHOR_PASSWORD: ${{ secrets.ANCHOR_PASSWORD }}
          FFMPEG_PATH: /usr/bin/ffmpeg
          LAST_VIDEO_ID: ${{ env.LAST_VIDEO_ID }}
