name: Youtube To Anchor Bot
on:
  push:
    branches:
      - main
    paths:
      - 'episode.json'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install Dependencies
        run: |
          npm install
          sudo apt-get update
          sudo apt-get -y install ffmpeg
      - name: Run Script
        run: |
          npm run start
        env:
          ANCHOR_EMAIL: ${{ secrets.ANCHOR_EMAIL }}
          ANCHOR_PASSWORD: ${{ secrets.ANCHOR_PASSWORD }}
          FFMPEG_PATH: /usr/bin/ffmpeg
      - name: Add and commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Atualizado via GitHub Action'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GIT }}
