name: Youtube To Anchor Bot
on:
  push:
    paths:
      - 'episode.json'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install Dependencies
        run: |
          npm install
          sudo apt-get update
          sudo apt-get -y install ffmpeg
      - name: Extrair lastVideoData.videoId de src/index.js
        run: |
          LAST_VIDEO_ID=$(node -p "require('./src/index.js').lastVideoData.videoId")
          echo "::set-output name=last_video_id::$LAST_VIDEO_ID"
      - name: Modificar episode.json
        run: |
          LAST_VIDEO_ID=$INPUT_LAST_VIDEO_ID
          jq ".ids[0] = \"$LAST_VIDEO_ID\"" episode.json > episode.tmp && mv episode.tmp episode.json
        env:
          ANCHOR_EMAIL: ${{ secrets.ANCHOR_EMAIL }}
          ANCHOR_PASSWORD: ${{ secrets.ANCHOR_PASSWORD }}
          FFMPEG_PATH: /usr/bin/ffmpeg
          INPUT_LAST_VIDEO_ID: ${{ steps.extrair_last_video_id.outputs.last_video_id }}
          
