name: Youtube To Anchor Bot
on:
  push:
    paths:
      - 'episode.json'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install Dependencies
        run: |
          npm install
          sudo apt-get update
          sudo apt-get -y install ffmpeg
      - name: Get video ID
        id: get-video-id
        run: |
          echo "::set-output name=video-id::$(node src/youtube-new-video/index.js)"
      - name: Set newVideoID environment variable
        run: echo "newVideoID=${{ steps.get-video-id.outputs.video-id }}" >> $GITHUB_ENV
      - name: Update episode.json
        run: |
          sed -i "s/\"videoId\": \".*\"/\"videoId\": \"${{ env.newVideoID }}\"/" episode.json
      - name: Run Script
        run: |
          npm run start
      - uses: EndBug/add-and-commit@v9
          add: 'episode.json'
          

        env:
          ANCHOR_EMAIL: ${{ secrets.ANCHOR_EMAIL }}
          ANCHOR_PASSWORD: ${{ secrets.ANCHOR_PASSWORD }}
          FFMPEG_PATH: /usr/bin/ffmpeg
