name: Youtube To Anchor Bot
on:
  schedule:
    - cron: '0 2 * * 6' # sábado às 23:00 (horário de Brasília)
    - cron: '0 17 * * 0' # domingo às 14:00 (horário de Brasília)
    - cron: '0 2 * * 0' # domingo as 23:00 (horário de Brasília)
    - cron: '0 15 * * 1' # segunda-feira às 12:00 (horário de Brasília) 
    - cron: '0 2 * * 4' # quarta-feira às 23:00 (horário de Brasília)
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install Dependencies
        run: |
          npm install
          sudo apt-get update
          sudo apt-get -y install ffmpeg
      - name: Run Script
        run: |
          npm run start
        env:
          ANCHOR_EMAIL: ${{ secrets.ANCHOR_EMAIL }}
          ANCHOR_PASSWORD: ${{ secrets.ANCHOR_PASSWORD }}
          FFMPEG_PATH: /usr/bin/ffmpeg
      - name: Add and commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Atualizado via GitHub Action'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GIT }}
