name: Youtube To Anchor Bot
on:
  push:
    paths:
      - 'episode.json'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install Dependencies
        run: |
          npm install
          sudo apt-get update
          sudo apt-get -y install ffmpeg
      - name: Get Last Video ID
        run: |
          echo "::set-env name=newVideoID::$(node ./src/youtube-new-video/index.js)"
      - name: Update episode.json
        run: |
          sed -i "s/\"ids\": \[[^]]*\]/\"ids\": [\${{ env.newVideoID }}]/" episode.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
